
#include "core-lib.h"

const char *fw_core_lib[MAX_CORE_LIBS] = {
    ": /  /mod swap drop ;\n",
    ": %  /mod drop ;\n",
    ": 1st 0 ;\n",
    ": 2nd 1 ;\n",
    ": 3rd 2 ;\n",
    ": 4th 3 ;\n",
    ": var-alloca ( size var-id -- ) 1 rot rot var-arr-alloca ;\n",
    ": var! ( val var-id -- ) 0 swap var-idx! ;\n",
    ": var@ ( var-id -- val ) 0 swap var-idx@ ;\n",
    ": 0> 0 > ;\n",
    ": 0< 0 < ;\n",
    ": 0= 0 = ;\n",
    ": 0<> 0 <> ;\n",
    ": 1+ 1 + ;\n",
    ": 1- 1 - ;\n",
    ": nop ;\n",
    ": compile-time ;\n",
    ": |> ;\n",
    ": cells ( n1 -- n2 ) cell * ;\n",
    ": interpret? STATE @ 0= ;\n",
    ": backref, HERE @ - , ;\n",
    ": begin immediate compile-time HERE @ ;\n",
    ": again immediate compile-time ['] branch , backref, ;\n",
    ": until immediate compile-time ['] 0branch , backref, ;\n",
    ": dip ( a xt -- a ) swap >r exec r> ;\n",
    ": keep ( a xt -- xt.a a ) over >r exec r> ;\n",
    ": 2over ( ) over over ;\n",
    ": 2drop ( a b -- ) drop drop ;\n",
    ": 3dup ( a b c -- a b c a b c) dup 2over rot ;\n",
    ": 3drop ( a b c -- ) 2drop drop ;\n",
    ": nl ( -- ) 0xA emit ;\n",
    ": space ( -- ) 0x20 emit ;\n",
    ": tab ( -- )  0x9 emit ;\n",
    ": +! ( n var -- ) tuck @ + swap ! ;\n",
    ": -! ( n var -- ) tuck @ swap - swap ! ;\n",
    ": i ( -- n ) rp@ 2 cells - @ ;\n",
    ": n ( -- n ) rp@ cell 3 * - @ ;\n",
    ": j ( -- n ) rp@ cell 4 * - @ ;\n",
    ": o ( -- n ) rp@ cell 5 * - @ ;\n",
    ": prepare-forward-ref ( -- a ) HERE @ 0 , ;\n",
    ": resolve-forward-ref ( a -- ) HERE @ over - swap ! ;\n",
    ": ifthen immediate compile-time ['] 0branch , prepare-forward-ref ;\n",
    ": else immediate compile-time ['] branch , prepare-forward-ref swap resolve-forward-ref ;\n",
    ": fi immediate compile-time resolve-forward-ref ;\n",
    ": ?dup ( a -- a a | 0 ) dup ifthen dup fi ;\n",
    ": do immediate compile-time ['] swap , ['] >r , ['] >r , 0 HERE @ ;\n",
    ": unloop r> r> r> 2drop >r ;\n",
    ": bounds ( start len -- limit start ) over + swap ;\n",
    ": loop immediate compile-time",
    "       ['] r> , ['] 1+ , ['] >r ,",
    "       ['] i , ['] n , ( index limit )",
    "       ['] >= ,",
    "       ['] 0branch , backref,",
    "       ifthen ( ?do ) resolve-forward-ref fi",
    "       ['] unloop , ;\n",
    ": while immediate compile-time ['] 0branch , prepare-forward-ref ;\n",
    ": repeat immediate compile-time swap ['] branch , backref, resolve-forward-ref ;\n",

}; 